### ISSUE TITLE
some misspelt in tutorial/python-excel.pdf---Page.11 

### ISSUE THREAD

**Issue by jJayyyyyyy** [python-excel/tutorial#5]
In paragraph 3 and 4

> bounded by **`and`** start index and an optional end index.

 Was it meant to be **`a`** ?
bounded by a start index and an optional end index

(PS: In para.5 is **`a`**)

**Comment by cjw296** [comment]
Your interpretation sounds correct.

Not sure what to suggest, this project is not seeing much in the way of active changes, so closing for now.
